# Generated by Django 3.2.4 on 2021-07-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('capacity_adults', models.IntegerField()),
                ('capacity_children', models.IntegerField()),
                ('bed', models.CharField(choices=[('Twins bed', 'Twins bed'), ('King bed', 'King bed')], max_length=25)),
                ('bathhub', models.BooleanField(default=True)),
                ('view', models.CharField(max_length=50)),
                ('pillow_menu', models.BooleanField(default=True)),
                ('balcone', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('gym_pool', models.BooleanField(default=True)),
                ('img_detail_rooms1', models.ImageField(blank=True, default='Image/roomType/Default/engin-akyurt-7VopMuTM9Ms-unsplash-1024x683.jpeg', null=True, upload_to='upload/roomType/')),
                ('img_detail_rooms2', models.ImageField(blank=True, default='Image/roomType/Default/julian-hochgesang-nqZv8jtwLTY-unsplash-1024x683.jpeg', null=True, upload_to='upload/roomType/')),
                ('img_detail_rooms3', models.ImageField(blank=True, default='Image/roomType/Default/mateo-fernandez-XTC538P_eWk-unsplash-768x1024.jpeg', null=True, upload_to='upload/roomType/')),
                ('img_detail_rooms4', models.ImageField(blank=True, default='Image/roomType/Default/radoslav-bali-X5P-0qUQS50-unsplash-819x1024.jpeg', null=True, upload_to='upload/roomType/')),
                ('img_detail_rooms5', models.ImageField(blank=True, default='Image/roomType/Default/yann-maignan-376909-unsplash-1024x683.jpeg', null=True, upload_to='upload/roomType/')),
                ('area', models.IntegerField()),
                ('img_vertical', models.ImageField(blank=True, default='Image/', null=True, upload_to='upload/roomType/roomIntro')),
                ('img_horizontal', models.ImageField(blank=True, default='Image/', null=True, upload_to='upload/roomType/roomIntro')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Repair', 'Repair')], max_length=10)),
                ('room_type_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomtype')),
            ],
        ),
    ]
