# Generated by Django 3.2.4 on 2021-07-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField(auto_now_add=True)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('idProof', models.CharField(max_length=20)),
                ('contactMail', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleTitle', models.CharField(max_length=100)),
                ('repeat', models.CharField(max_length=10)),
                ('description', models.TextField(default='')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=50)),
                ('paymentDate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('saleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.sale')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='saleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.sale'),
        ),
    ]
