# Generated by Django 3.2.4 on 2021-07-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('idProof', models.CharField(max_length=20)),
                ('contactMail', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleTitle', models.CharField(max_length=100)),
                ('repeat', models.CharField(max_length=10)),
                ('description', models.TextField(default='')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paymentType', models.CharField(choices=[('Momo', 'Momo'), ('Visa/Debit/Mastercard', 'Visa/Debit/Mastercard'), ('Paypal', 'Paypal')], max_length=50)),
                ('paymentDate', models.DateTimeField(auto_now=True)),
                ('checkin', models.DateField(default='')),
                ('checkout', models.DateField(default='')),
                ('status', models.BooleanField(default=False)),
                ('customerID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
                ('saleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField(auto_now_add=True)),
                ('checkin', models.DateField(default='')),
                ('checkout', models.DateField(default='')),
                ('paymentID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.payment')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
