# Generated by Django 3.2.4 on 2021-07-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_customer_contactnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contactNum',
            field=models.CharField(default='0123456789', max_length=10),
        ),
    ]
