# Generated by Django 3.2.4 on 2021-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210718_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
