# Generated by Django 3.2.4 on 2021-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
