# Generated by Django 3.2.4 on 2021-07-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_customer_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='saleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.sale'),
        ),
    ]
