# Generated by Django 3.2.4 on 2021-07-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='address',
            field=models.TextField(default='04 Hoang Van Thu Street, Sa Pa, Lao Cai, Viet Nam'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/Hotel.An.Khang/', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='instagram',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(default='+(84) 85 266 2000', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='twitter',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='zalo',
            field=models.CharField(default='https://zalo.me/0852662000', max_length=255),
        ),
    ]
