# Generated by Django 3.2.4 on 2021-07-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu', models.CharField(default='Signature Menu', max_length=100)),
                ('img_menu', models.ImageField(blank=True, default='Image/diningpage/menuImage/lunch.jpeg', null=True, upload_to='upload/dining/menu')),
            ],
        ),
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_food', models.CharField(default='Salted Fried Chicken', max_length=100)),
                ('description_food', models.CharField(default='Mint parsley with apple cider vinegar, salt, sugar & spices', max_length=255)),
                ('price_food', models.IntegerField()),
                ('special', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.IntegerField(default=0)),
                ('name_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='diningPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_bg_header', models.ImageField(blank=True, default='Image/homepage/RoomImage/149368628.jpeg', null=True, upload_to='upload/diningPage/header')),
                ('title_header1', models.CharField(default='Homewood Suite', max_length=50)),
                ('title_header2', models.CharField(default='Make Yourself at Home', max_length=50)),
                ('img_slide1', models.ImageField(blank=True, default='Image/diningpage/slideImage/louis-hansel-shotsoflouis-iBfVwYwA3ek-unsplash-1024x683.jpeg', null=True, upload_to='upload/diningPage/slide')),
                ('img_slide2', models.ImageField(blank=True, default='Image/diningpage/slideImage/the-chef-is-garnishing-appetizer-dish-PDHYM4B-683x1024.jpeg', null=True, upload_to='upload/diningPage/slide')),
                ('img_slide3', models.ImageField(blank=True, default='Image/diningpage/slideImage/asiya-kiev-SiwrpBnxDww-unsplash-1024x683.jpeg', null=True, upload_to='upload/diningPage/slide')),
                ('img_slide4', models.ImageField(blank=True, default='Image/diningpage/slideImage/fresh-salmon-with-dill-food-photography-recipe-JMQKHUY-741x1024.jpeg', null=True, upload_to='upload/diningPage/slide')),
                ('img_intro1', models.ImageField(blank=True, default='Image/diningpage/dishImage/fresh-salmon-with-dill-food-photography-recipe-JMQKHUY-768x1061.jpeg', null=True, upload_to='upload/diningPage/intro')),
                ('img_intro2', models.ImageField(blank=True, default='Image/diningpage/dishImage/elegant-restaurant-table-setting-service-for-P8HYX7H-768x513.jpeg', null=True, upload_to='upload/diningPage/intro')),
                ('menu1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu1', to='menu.menu')),
                ('menu2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu2', to='menu.menu')),
            ],
        ),
    ]
